# Generated by Django 2.0.3 on 2018-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.TextField(max_length=20)),
                ('price_single', models.IntegerField()),
                ('avail_single', models.IntegerField()),
                ('price_double', models.IntegerField()),
                ('avail_double', models.IntegerField()),
            ],
        ),
    ]
