# Generated by Django 2.0.3 on 2018-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
