# Generated by Django 2.0.3 on 2018-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0003_auto_20180512_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='month',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='month_year',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
