# Generated by Django 2.0.3 on 2018-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0004_auto_20180515_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='year',
        ),
    ]
