# Generated by Django 2.0.3 on 2018-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0005_auto_20180515_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='month',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='month_year',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
